---

- hosts: all
  become: yes

## just enabled below firewall commands based of https://docs.oracle.com/en/operating-systems/olcne/1.1/start/ports.html
## other docs dont show these, but going to try and then document later
#sudo ufw allow 2379/tcp comment "k8 etcd server client API"
#sudo ufw allow 2380/tcp comment "k8 etcd server client API"
#sudo ufw allow 6443/tcp comment "k8 API server"
#sudo ufw allow 8090/tcp comment "k8 Platform Agent"
#sudo ufw allow 8091/tcp comment "k8 Platform API Server"
#sudo ufw allow 10250/tcp comment "k8 kubelet API server"
#sudo ufw allow 10251/tcp comment "k8 kube-scheduler"
#sudo ufw allow 10252/tcp comment "k8 kube-controller-manager"
#sudo ufw allow 10255/tcp comment "k8 kubelet API server for read-only access with no authentication"
#
#after this, i got error on - 
#$ kubectl get nodes
#The connection to the server localhost:8080 was refused - did you specify the right host or port?
#
#ah, found this on kubernetes site - 
#https://kubernetes.io/docs/reference/networking/ports-and-protocols/
#
#https://admantium.com/blog/kube11_k8s_with_kubeadm_tutorial/
#https://www.fosstechnix.com/how-to-install-kubernetes-cluster-on-ubuntu/
#

  tasks:
  - name: Control Pane Only - Allow 6443 for k8 API server
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      port: '6443'
      comment: k8 API server
    when: "'k8_nodes_control' in group_names"
  
  - name: Control Pane Only - Allow 2379-2380 for etcd server client API
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      port: 2379:2380
      comment: k8 etcd server client API
    when: "'k8_nodes_control' in group_names"
  
  - name: Control Pane Only - Allow 10250 for k8 Kubelet API
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      port: '10250'
      comment: k8 Kubelet API
    when: "'k8_nodes_control' in group_names"
  
  - name: Control Pane Only - Allow 10259 for k8 kube-scheduler
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      port: '10259'
      comment: k8 kube-scheduler
    when: "'k8_nodes_control' in group_names"
  
  - name: Control Pane Only - Allow 10257 for k8 kube-controller-manager
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      port: '10257'
      comment: k8 kube-controller-manager
    when: "'k8_nodes_control' in group_names"
  
  - name: Worker Nodes Only - Allow 10250 for k8 Kubelet API
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      port: '10250'
      comment: k8 Kubelet API
    when: "'k8_nodes_worker' in group_names"
  
  
  - name: Worker Nodes Only - Allow 30000-32767 for k8 NodePort Services
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      port: 30000:32767
      comment: k8 NodePort Services
    when: "'k8_nodes_worker' in group_names"


