---

#--------------------------------------------------------------------------------
#prerequisites -  steps to do on *BOTH* master and worker nodes
#
#run apt update
#
#add the host/ip records to all /etc/hosts  and make sure can ping each other
#
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------

# - name : check if new nodes are accessible	NOT-WORKING
#   register: reg_ping
#   debug:
#     msg: reg_ping

# - name : check if host satisfies minimum memory criteria (2 GB)
#   debug: 
#     var: ansible_memory_mb
#   debug: 
#     msg: "total RAM is {{ ansible_memory_mb.real.total }}"
#   fail: 
#     msg: "not enough RAM"
#   when: ansible_memory_mb.real.total < 4096

# - name: After version 2.7 both 'msg' and 'fail_msg' can customize failing assertion message
#   ansible.builtin.assert:
#     that:
#       - my_param <= 100
#       - my_param >= 0
#     fail_msg: "'my_param' must be between 0 and 100"
#     success_msg: "'my_param' is between 0 and 100"

#   - name : check if host has minimum memory criteria (2 GB)       NOT-WORKING
#     debug:
#       msg: "total RAM is {{ ansible_memory_mb.real.total }}"
#     ansible.builtin.assert:
#       that:
#         - ansible_memory_mb.real.total >= 4096
#       fail_msg: "'ansible_memory_mb.real.total' must be above 4096"
#       success_msg: "'ansible_memory_mb.real.total' is above 4096"
  
#   - name: check memory 2
#     debug: var=ansible_memory_mb
#     debug: msg="total RAM is {{ ansible_memory_mb.real.total }}"
#     fail: 
#       msg: "not enough RAM"
#     when: ansible_memory_mb.real.total < 4096


# below 2 associated tasks work, but i think i commented because it does the fail and not proceed to the next tasks
# - name: check memory ---testing--
#   debug: 
#     var=ansible_memory_mb
#   debug: 
#     msg: "total RAM is {{ ansible_memory_mb.real.total }}"
# 
# - name: do the fail
#   fail: 
#     msg: "not enough RAM (should be atleast 2 GB)"
#   when: ansible_memory_mb.real.total < 2048

# appends a block of hostname and ip records to bottom of /etc/hosts file
# giving task name will make it seem in the output as if 2 seperate tasks are being done
# it still does but not that explicit
# - name: append host and ip records to /etc/hosts file (CALLS from another ROLE)
- ansible.builtin.include_role:
    name: server_configure
    # use only this task, name should match the yml file
    tasks_from: append_records_to_etc_hosts_file

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
# Check required ports 
  - import_tasks: all_firewall_changes.yml
    when: "'k8_nodes_private_ips' in group_names"
