---
# tasks file for kubernetes

# i need to understand properly if docker is ever needed for kubernetes, i can make it use containerd only i think - 
# $ kubectl get nodes -o wide
# NAME               STATUS   ROLES           AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
# acg-k8-controlp1   Ready    control-plane   36m   v1.26.0   172.31.104.228   <none>        Ubuntu 22.04.2 LTS   5.19.0-1024-aws   containerd://1.6.12


- hosts: k8_nodes_private_ips
#- hosts: all
  become: true

  tasks:
#    - import_tasks: check_prerequisites.yml
    when: "'k8_nodes_private_ips' in group_names"
  - import_tasks: phase_1_steps_on_all_k8_nodes.yml
    when: "'k8_nodes_private_ips' in group_names"
  - import_tasks: phase_2_steps_on_k8_control_pane_nodes.yml
    when: "'k8_nodes_control' in group_names"
  - import_tasks: phase_3_steps_on_k8_worker_nodes.yml
    when: "'k8_nodes_worker' in group_names"



