---

#--------------------------------------------------------------------------------
#prerequisites -  steps to do on *BOTH* master and worker nodes
#
#run apt update
#
#add the host/ip records to all /etc/hosts  and make sure can ping each other
#
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------

 - name : check if new nodes are accessible	NOT-WORKING
   register: reg_ping
   debug:
     msg: reg_ping
   tags:
     - just-this-task

# - name : check if host satisfies minimum memory criteria (2 GB)
#   debug: 
#     var: ansible_memory_mb
#   debug: 
#     msg: "total RAM is {{ ansible_memory_mb.real.total }}"
#   fail: 
#     msg: "not enough RAM"
#   when: ansible_memory_mb.real.total < 4096

# - name: After version 2.7 both 'msg' and 'fail_msg' can customize failing assertion message
#   ansible.builtin.assert:
#     that:
#       - my_param <= 100
#       - my_param >= 0
#     fail_msg: "'my_param' must be between 0 and 100"
#     success_msg: "'my_param' is between 0 and 100"

#   - name : check if host has minimum memory criteria (2 GB)       NOT-WORKING
#     debug:
#       msg: "total RAM is {{ ansible_memory_mb.real.total }}"
#     ansible.builtin.assert:
#       that:
#         - ansible_memory_mb.real.total >= 4096
#       fail_msg: "'ansible_memory_mb.real.total' must be above 4096"
#       success_msg: "'ansible_memory_mb.real.total' is above 4096"
  
#   - name: check memory 2
#     debug: var=ansible_memory_mb
#     debug: msg="total RAM is {{ ansible_memory_mb.real.total }}"
#     fail: 
#       msg: "not enough RAM"
#     when: ansible_memory_mb.real.total < 4096


# below 2 associated tasks work, but i think i commented because it does the fail and not proceed to the next tasks
# - name: check memory ---testing--
#   debug: 
#     var=ansible_memory_mb
#   debug: 
#     msg: "total RAM is {{ ansible_memory_mb.real.total }}"
# 
# - name: do the fail
#   fail: 
#     msg: "not enough RAM (should be atleast 2 GB)"
#   when: ansible_memory_mb.real.total < 2048


-- i did not check previously if selinux is disabled, which is a requirement
run  getenforce (sudo apt install policycoreutils selinux-utils selinux-basics   if not there)
output should be "Disabled"
can also run   sestatus
output should be "SELinux status:                 disabled"








