---
- hosts: all
  gather_facts: yes
  become: true
  vars:
    configure_new_server: true
  
  tasks:

#--------------------------------------------------------------------------------
#prerequisites -  steps to do on *BOTH* master and worker nodes
#
#run apt update
#
#add the host/ip records to all /etc/hosts  and make sure can ping each other
#
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------

    - name: Display all gathered facts
      debug:
        var: ansible_facts

    - name: Show the total available RAM
      debug:
        msg: "Total RAM is {{ ansible_memory_mb.real.total }} MB"

    - name: Fail if RAM is less than 2 GB (2048 MB)
      fail:
        msg: "Not enough RAM. Host has only {{ ansible_memory_mb.real.total }} MB. Minimum required is 2048 MB."
      when: ansible_memory_mb.real.total < 2048

    - name: Print a warning if RAM is between 2 GB and 4 GB
      debug:
        msg: "Warning: RAM is low at {{ ansible_memory_mb.real.total }} MB. Consider upgrading."
      when: ansible_memory_mb.real.total >= 2048 and ansible_memory_mb.real.total < 4096



  # below 2 associated tasks work, but i think i commented because it does the fail and not proceed to the next tasks
  # - name: check memory ---testing--
  #   debug: 
  #     var=ansible_memory_mb
  #   debug: 
  #     msg: "total RAM is {{ ansible_memory_mb.real.total }}"
  # 
  # - name: do the fail
  #   fail: 
  #     msg: "not enough RAM (should be atleast 2 GB)"
  #   when: ansible_memory_mb.real.total < 2048
  
  
  # -- i did not check previously if selinux is disabled, which is a requirement
  # run  getenforce (sudo apt install policycoreutils selinux-utils selinux-basics   if not there)
  # output should be "Disabled"
  # can also run   sestatus
  # output should be "SELinux status:                 disabled"
  







