---


#--------------------------------------------------------------------------------
#phase 2 -  steps to do on *ONLY* on control pane
# that too only on 1 control plane and not the rest, if we have any
# on the rest of control panes, we will run the join as master later on
#
#configuring cluster using kubeadm
#
#kubeadm init
#do the kube config 3 steps
#
#save the kubeadm join command info (will need to run it on the worker nodes)
#
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------

# output of manual run at command line below - 

# running with --v=5 is very useful

sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=172.31.20.249
[sudo] password for cloud_user:
[init] Using Kubernetes version: v1.27.1
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2023-04-30T17:16:46Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"
unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"                                                               , error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
cloud_user@acg-k8-controlp1:~/git-projects/ansible_repo/roles/kubernetes/tasks
$ sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=172.31.20.249 --v=5
I0430 17:17:15.441287    1550 initconfiguration.go:117] detected and using CRI socket: unix:///var/run/containerd/containerd.sock
I0430 17:17:15.441373    1550 kubelet.go:196] the value of KubeletConfiguration.cgroupDriver is empty; setting it to "systemd"
I0430 17:17:15.453242    1550 version.go:187] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
[init] Using Kubernetes version: v1.27.1
[preflight] Running pre-flight checks
I0430 17:17:15.754703    1550 checks.go:563] validating Kubernetes and kubeadm version
I0430 17:17:15.754832    1550 checks.go:168] validating if the firewall is enabled and active
I0430 17:17:15.766072    1550 checks.go:203] validating availability of port 6443
I0430 17:17:15.766254    1550 checks.go:203] validating availability of port 10259
I0430 17:17:15.766307    1550 checks.go:203] validating availability of port 10257
I0430 17:17:15.766353    1550 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0430 17:17:15.766381    1550 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0430 17:17:15.766402    1550 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0430 17:17:15.766422    1550 checks.go:280] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0430 17:17:15.766443    1550 checks.go:430] validating if the connectivity type is via proxy or direct
I0430 17:17:15.766473    1550 checks.go:469] validating http connectivity to first IP address in the CIDR
I0430 17:17:15.766797    1550 checks.go:469] validating http connectivity to first IP address in the CIDR
I0430 17:17:15.766829    1550 checks.go:104] validating the container runtime
I0430 17:17:15.805613    1550 checks.go:639] validating whether swap is enabled or not
I0430 17:17:15.805761    1550 checks.go:370] validating the presence of executable crictl
I0430 17:17:15.806033    1550 checks.go:370] validating the presence of executable conntrack
I0430 17:17:15.806104    1550 checks.go:370] validating the presence of executable ip
I0430 17:17:15.806134    1550 checks.go:370] validating the presence of executable iptables
I0430 17:17:15.806174    1550 checks.go:370] validating the presence of executable mount
I0430 17:17:15.806212    1550 checks.go:370] validating the presence of executable nsenter
I0430 17:17:15.806250    1550 checks.go:370] validating the presence of executable ebtables
I0430 17:17:15.806286    1550 checks.go:370] validating the presence of executable ethtool
I0430 17:17:15.806320    1550 checks.go:370] validating the presence of executable socat
I0430 17:17:15.806356    1550 checks.go:370] validating the presence of executable tc
I0430 17:17:15.806388    1550 checks.go:370] validating the presence of executable touch
I0430 17:17:15.806423    1550 checks.go:516] running all checks
I0430 17:17:15.830410    1550 checks.go:401] checking whether the given node name is valid and reachable using net.LookupHost
I0430 17:17:15.830454    1550 checks.go:605] validating kubelet version
I0430 17:17:15.923668    1550 checks.go:130] validating if the "kubelet" service is enabled and active
I0430 17:17:15.937197    1550 checks.go:203] validating availability of port 10250
I0430 17:17:15.937291    1550 checks.go:329] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0430 17:17:15.937355    1550 checks.go:329] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0430 17:17:15.937399    1550 checks.go:203] validating availability of port 2379
I0430 17:17:15.937452    1550 checks.go:203] validating availability of port 2380
I0430 17:17:15.937504    1550 checks.go:243] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2023-04-30T17:17:15Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:260
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:232
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        cmd/kubeadm/app/cmd/init.go:111
github.com/spf13/cobra.(*Command).execute
        vendor/github.com/spf13/cobra/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
        vendor/github.com/spf13/cobra/command.go:1040
github.com/spf13/cobra.(*Command).Execute
        vendor/github.com/spf13/cobra/command.go:968
k8s.io/kubernetes/cmd/kubeadm/app.Run
        cmd/kubeadm/app/kubeadm.go:50
main.main
        cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598
cloud_user@acg-k8-controlp1:~/git-projects/ansible_repo/roles/kubernetes/tasks
$

--
i am seeing the CRI error ..

