---


#--------------------------------------------------------------------------------
#phase 2 -  steps to do on *ONLY* on control pane
# that too only on 1 control plane and not the rest, if we have any
# on the rest of control panes, we will run the join as master later on
#
#configuring cluster using kubeadm
#
# see the 6443 refused below and maybe do the (below section called -6443-) containerd config change and restart here itself
#
#kubeadm init    (and do with --v=5)
# this has given me diff types of errors all the time during pre-flight checks, like such - 
#     sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=172.31.100.23 --v=5
#     sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --kubernetes-version 1.26.0 --v=5   (this one i did for 1.26 version worked on 07-May-2023, best to use this version for now)

#           [preflight] Running pre-flight checks                                                                           
#           error execution phase preflight: [preflight] Some fatal errors occurred:                                        
#                   [ERROR CRI]: container runtime is not running: output: time="2023-05-03T09:21:13Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containe
#           rd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"                    
#           , error: exit status 1
# i followed 1 article which told to mv /etc/containerd/config.toml to config.toml.bak and restart containerd and then do kubeadm and that seems to have worked for me  (but that was for 1.27 kubectl/let/adm install, i did not have do this for 1.26 version)

# -6443-
# The connection to the server 192.168.1.2:6443 was refused - did you specify the right host or port?
# above was one of the worst errors that gave me a lot of trouble, i think i spent nearly 20 full hours tblshootting and re-installing again and again
# below links helped me with fixing it
# https://discuss.kubernetes.io/t/the-connection-to-the-server-192-168-1-2-6443-was-refused-did-you-specify-the-right-host-or-port/22260
# https://www.linuxtechi.com/install-kubernetes-cluster-on-debian/
# https://stackoverflow.com/questions/70849989/kube-apiserver-docker-shutting-down-got-signal-terminated/74695838#74695838
# https://www.vnoob.com/2022/12/kubectl-6443-connection-refused/
# i backed up and went to /etc/containerd/config.toml around line 125 (only 1 reference for SystemdCgroup) and changed SystemdCgroup = true and bounced containerd



#do the kube config 3 steps
#   mkdir -p $HOME/.kube
#   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#   sudo chown $(id -u):$(id -g) $HOME/.kube/config
#
#save the kubeadm join command info into a text file for LATER (will need to run it on the worker nodes) and make sure to RUN IT AS SUDO
#
#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------











