
---

# i have just taken this from another place
# need to make it take a pre-defined variable of group name
# creates or ensures that the group user XXXX  exists
- name : create group user tomcat
  group:
    name: tomcat
    state: present
