---

# appends a block of hostname and ip records to bottom of /etc/hosts file
- name: append host and ip records to /etc/hosts file
  blockinfile:
    path: /etc/hosts
    state: present
    insertafter: EOF
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      172.31.20.249   acg-k8-controlp1
      172.31.18.228   acg-k8-controlp2
      172.31.17.206   acg-k8-worker1
      172.31.27.142   acg-k8-worker2
      172.31.31.203   acg-k8-worker3
