---
# some other untested article for ref - https://www.middlewareinventory.com/blog/ansible-update-etc-hosts-file-across-all-hosts/

# appends a block of hostname and ip records to bottom of /etc/hosts file
- name: append host and ip records to /etc/hosts file
  blockinfile:
    path: /etc/hosts
    state: present
    insertafter: EOF
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      172.31.100.23       acg-k8-controlp1
      172.31.111.98       acg-k8-controlp2
      172.31.96.38        acg-k8-worker1
      172.31.104.153      acg-k8-worker2
      172.31.107.115      acg-k8-worker3
