---


- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400             # run "update_cache=yes" only if the last one was more than these many seconds ago (1 day)
