---
- hosts: all
  become: yes

  tasks:
  - name: Print the hostnames in inventory
    debug:
      msg: "{{ inventory_hostname }}"

  - name: Change the remote hostname using inventory name
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

  - name: Here we are checking ansible_hostname (actual REMOTE host name from returned values)
    debug:
      msg: "a-hostname={{ ansible_hostname }}  a-fqdn={{ ansible_fqdn }}  a-nodename={{ ansible_nodename }}"

