
---

# - name: Adding users - using with_items
#   user:
#     name: "{{ item }}"
#     state: present
#   with_items:
#      - john
#      - mike
#      - andrew

 - name: Adding users - using loop
   user:
     name: '{{ item.name }}'
     uid: '{{ item.uid }}'
     state: present

   loop:
     - name: roger
       uid: 1020
     - name: tom
       uid: 1030
     - name: winston
       uid: 1040

# - name: Adding users - using loop - json  (NOT WORKING YET)
#   user:
#     name: "{{ item.name }}"
#     uid: "{{ item.uid }}"
#     state: present
#
#     loop:
#       - { name: john ,   uid: 1020 }
#       - { name: mike ,   uid: 1030 }
#       - { name: andrew , uid: 1040 }
#     # this in JSON format is same as above


