---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html

    - name: Add Docker apt key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'
        force: true
      register: add_repository_key

# i suppose we can use this in place of curl command
- name: Download Tomcat using get_url module
  become: true
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz 
    dest: /tmp
    mode: 0755
    #checksum: sha512:5bdea5414713c9ba39e226f062701fa14998b1a798c9750f956a0f59b5edabb8d83af9ec9f81cf9f47fa92c21b560c9b2be1b543d0bd8f1b49579b69101d3a8f
    #group: tomcat
    #owner: tomcat

# Downloading the tomcat package
- name: Download Tomcat
  get_url: 
     url:  "{{ tomcat_download_url }}"
     dest: "{{ tomcat_download_location }}"


