- name: Ensure pwgen is installed
  apt:
     name: pwgen
     state: present
     update_cache: True

- name: Generate password
  shell: pwgen -N 1 15
  register: mypass

- name: Print the generated password
  ansible.builtin.debug:
#    msg: "The mypass object output is {{ mypass }}"
    msg: "The password is {{ mypass.stdout }}"
