---
# tasks file for server_configure

 - hosts: all
   become: true

   tasks:
#   - import_tasks: append_records_to_etc_hosts_file.yml
#   - import_tasks: run_shell_cmd_lsb_release.yml
   - import_tasks: generate_password.yml



