---
# tasks file for server_configure
# though this is a main.yml file, it is still a TASKS file and not a playbook file
# so cannot contain play-level keywords like hosts, vars, roles, or tasks.


- name: Print the hostnames in inventory
  debug:
    msg: "Printing hostname in inventory -> {{ inventory_hostname }}"

- name: Import tasks from change_hostname.yml
  include_tasks: 
     file: change_hostname.yml
#      tags:
#        - just-this-task

- name: Import tasks from check_disk_space.yml
  include_tasks: 
     file: check_disk_space.yml
  tags:
    - just-this-task

###- name: Import tasks from apt_update_and_upgrade.yml
###  import_tasks: apt_update_and_upgrade.yml
###
###- name: Import tasks from role server_configure - append_records_to_etc_hosts_file.yml
###  import_tasks: append_records_to_etc_hosts_file.yml
###
###- name: Import tasks from role server_configure - swap.yml
###  import_tasks: swap.yml
###


# --- below todo ---
#    - import_tasks: append_records_to_etc_hosts_file.yml
#    - import_tasks: generate_password.yml
#    - import_tasks: add_user.yml

#     - name: Include the example role and run its tasks (at this point in the sequence of tasks)
#       #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_role_module.html
#       # also read about import_role
#       include_role:
#         name: example

#    - import_tasks: install_with_apt.yml
# lot of things in docker.yml to copy over here in server configure


