---
# tasks file for server_configure

 - hosts: all
   become: true
   vars_files:
      - "../vars/main.yml"

   tasks:
#    - import_tasks: append_records_to_etc_hosts_file.yml
    - import_tasks: run_shell_cmd_lsb_release.yml
#    - import_tasks: generate_password.yml
#    - import_tasks: add_user.yml
    - import_tasks: install_with_apt.yml
# lot of things in docker.yml to copy over here in server configure


