---

# just to test the shell module to run remote command and check output
- name: check OS information 
  shell: 
    cmd: lsb_release -a
  register: reg_os_info     # output is saved in this variable
  tags:
    - check_release

- name: print the variable
  debug:
    msg: "var = {{ reg_os_info.stdout_lines }} "
  tags:
    - check_release


- name: copy a file from ansible server onto remote hosts into /tmp dir
  copy:
    src: /etc/hostname
    dest: /tmp/
    mode: 0755
  tags:
    - check_release

