
---

# just to test the shell module to run remote command and check output
- name: check OS information 
  shell: 
    cmd: lsb_release -a
  register: reg_os_info     # output is saved in this variable

- debug:
    var="reg_os_info.stdout_lines + [ reg_os_info.stderr_lines ]"
