---

- hosts: all
  become: true

  tasks:
  - name: Check if swap is enabled                # TESTED-AND-WORKS
    # grep -w because I don't want /swap matching /swapfile, for example
    ansible.builtin.shell: "/sbin/swapon --show"                            # should show no rows and return code of 0 if no swap
    register: reg_fstab_swap_count
    tags:
      - swap-check
  
  - debug:                            # TESTED-AND-WORKS
      var: reg_fstab_swap_count.stdout
    tags:
      - swap-check
  
  
  - name: Disable swap                        # TESTED-AND-WORKS
    become: true
    command: /sbin/swapoff -a
    tags:
      - swap-disable

#  
#  - name: Ensure swap file doesn't exist (if configured)
#    file:
#      path: "{{ swap_file_path }}"
#
#  - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
#    replace:
#      path: /etc/fstab
#      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
#      replace: '# \1'
#
## if swap on, will look something like this - 
## $ free -h
##              total       used       free     shared    buffers     cached
## Mem:           14G        12G       2.7G       232K       512M       2.8G
## -/+ buffers/cache:       8.9G       6.0G
## Swap:         8.0G       289M       7.7G
## 
## $ grep swap /etc/fstab
## /dev/mapper/rootvg-swapvol swap                    swap    defaults        0 0
##
## $ /sbin/swapon -s
## Filename                                Type            Size    Used    Priority
##/dev/dm-1                               partition       8388604 296036  -1
#
#
##turn off swap and comment out /etc/fstab if there is any swap
##e.g. - /dev/hda6   swap     swap   defaults        0    0
##    or  free command shows ->
##Swap:          2047           5        2042
##$ grep -i --color swap /proc/meminfo
##SwapCached:        39196 kB
##SwapTotal:       8388604 kB
##SwapFree:        7995420 kB
##https://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/
#
# https://codeberg.org/ansible/swap/src/branch/main/tasks/swap.yml
# https://supportex.net/blog/2014/10/ansible-add-swap-linux-box/
# https://github.com/geerlingguy/ansible-role-swap
# https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/

