---
# test_main.yml
# this is a PLAYBOOK where we can test the role's tasks files or individual tasks

- hosts: all
  gather_facts: yes
  become: true

  vars:
    v_run_task: "v_fm_append_to_hosts_file"

  tasks:

    # First inclusion for IS1-03
    # all tasks from this file will be included here.
    # This structure is useful for testing or isolating specific tasks from a role or task file. It allows you to experiment with different configurations or sets of tasks without altering your main role.
    - name: Run task IS1-03 first (which is the 3rd task of include-1 tasks file)
      ansible.builtin.include_tasks: ../../server_configure/tasks/include_sample_1.yml
      vars:
        # set this variable with a specific value so that it can be used within include_sample_1.yml to conditionally run only specific tasks 
        v_run_task: "IS1-03"

    # Second inclusion for IS1-01
    - name: Run task IS1-01 second (which is the 1st task of include-1 tasks file) 
      ansible.builtin.include_tasks: ../../server_configure/tasks/include_sample_1.yml
      vars:
        v_run_task: "IS1-01"
    
    - name: Run task IS2-04 first (which is the 4th task in the include-2 tasks file)
      ansible.builtin.include_tasks: ../../server_configure/tasks/include_sample_2.yml
      vars:
        v_run_task: "IS2-04"

    - name: Run task IS2-01 second (which is the 1st task in the include-2 tasks file)
      ansible.builtin.include_tasks: ../../server_configure/tasks/include_sample_2.yml
      vars:
        v_run_task: "IS2-01"


    - name: Run task IS2-01 second (which is the 1st task in the include-2 tasks file)
      ansible.builtin.include_tasks: ../../server_configure/tasks/include_sample_2.yml
      vars:
        v_run_task: "IS2-01"

    - name: Append Hostname and IP records block to remote hosts from file_management.yml
      ansible.builtin.include_tasks: ../../server_configure/tasks/file_management.yml
      when: (v_run_task | default('')) == "v_fm_append_to_hosts_file"       # if v_run_task is missing, it defaults to an empty string '' and doesn't break execution.

