---

- hosts: all
  vars:
    greetings: Hello World!
    site: www.example.com

  tasks:

  - name: Print the value of local defined variables
    debug:
      msg: "{{ greetings }}, Welcome to {{ site }}. We are on host {{ ansible_hostname }}"
