---
# roles/server_configure/vars/main.yml

# vars file for server_configure

# for the task: Install various packages using variable defined in var directory
prerequisite_packages:
  - curl
  - wget
  - vim

# other common packages required to be installed
common_packages:
  - get
  - tar
  - python3-pip

# distribution based packages
distribution_based_packages:
  Debian:
    - dnsutils
    - build-essential
    - python3-dev
  RedHat:
    - bind-utils
    - gcc
    - python3-devel

# for the task: FM-20 - Create an nginx config file using a jinja template file
server_name: example.com
document_root: /var/www/html

