
---

# creates or ensures that the user tomcat exists
- name : 04 / create user tomcat
  user:
    name: tomcat
    groups: tomcat              # default = empty
    state: present
    shell: /bin/false            # default = /bin/bash
    create_home: true           # default = true
    home: /opt/tomcat           # default = /home/<username>
